[features]
seeds = false
skip-lint = false

[programs.localnet]
freelance_platform = "xXBP5XebxLWY2bG3691JeTbCRmcjjncAm5n7jMvVevm"

[programs.mainnet]
freelance_platform = "xXBP5XebxLWY2bG3691JeTbCRmcjjncAm5n7jMvVevm"

[programs.devnet]
freelance_platform = "xXBP5XebxLWY2bG3691JeTbCRmcjjncAm5n7jMvVevm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"